[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[build.env]
NIXPACKS_JDK_VERSION = "21"


[deploy]
startCommand = "java -jar target/hms-backend-1.0.0.jar"
restartPolicyType = "ON_FAILURE"


